[package]
name = "newtype_array"
description = "A macro to help implementing the standard derived traits on newtype arrays"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
keywords = ["array", "arrays", "const", "generics"]

